server:
  port: 8188

management:
  endpoints:
    web:
      exposure:
        include: refresh


spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/gateway
    url: jdbc:h2:file:../data/Bulk/bulk;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;
    username: BulkTransferService
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  task:
    execution:
      thread-name-prefix: bulk-transfer-service-task-
      pool:
        core-size: 10
        max-size: 100
        queue-capacity: 10000